INDUSTRY_OPTIONS = [
    "Healthcare",
    "FinTech",
    "Retail",
    "Energy",
    "SaaS",
    "Telecom",
    "Logistics",
    "Manufacturing",
    "Public Sector",
    "Consumer Goods",
    "Media",
    "Insurance",
    "Automotive",
    "Travel",
    "Education",
]

FUNCTION_OPTIONS = [
    "Strategy",
    "Pricing",
    "GTM",
    "Operations",
    "Supply Chain",
    "Product",
    "Sales",
    "Marketing",
    "Finance",
    "Risk/Compliance",
    "Data/AI",
    "Customer Experience",
    "Procurement",
    "HR",
    "Digital Transformation",
]

ROLE_LEVELS = ["Analyst", "Manager", "Director", "VP", "CxO"]

GEOGRAPHY_OPTIONS = [
    "Any",
    "North America",
    "Europe",
    "APAC",
    "LATAM",
    "Middle East",
    "Africa",
]

EXPERTS = [
    {
        "id": "EXP-001",
        "name": "Samantha Lee",
        "headline": "Former VP Pricing, Global MedTech",
        "industryTags": ["Healthcare", "Manufacturing"],
        "functionTags": ["Pricing", "Strategy"],
        "roleLevel": "VP",
        "yearsExperience": 18,
        "geography": "North America",
        "languages": ["English"],
        "ratePerHour": 850,
        "credentials": {
            "education": "MBA, Wharton",
            "formerCompanies": ["MedNova", "Baxwell Health"],
            "notableProjects": ["Global price corridor redesign", "Value-based pricing rollout"],
            "publications": ["Pricing governance in MedTech"],
        },
        "expertiseSummary": "Led pricing strategy across devices and diagnostics with focus on value-based models.",
        "topicKeywords": ["pricing", "value-based", "governance", "portfolio", "rebate"],
        "availability": "Available in 2 weeks",
        "cidCleared": True,
        "complianceFlags": ["No MNPI", "No confidential client info"],
    },
    {
        "id": "EXP-002",
        "name": "Diego Martinez",
        "headline": "Operations Director, Global Retail Supply Chain",
        "industryTags": ["Retail", "Logistics"],
        "functionTags": ["Operations", "Supply Chain"],
        "roleLevel": "Director",
        "yearsExperience": 15,
        "geography": "LATAM",
        "languages": ["Spanish", "English"],
        "ratePerHour": 420,
        "credentials": {
            "education": "MSc, Industrial Engineering",
            "formerCompanies": ["Mercado Uno", "FastCart"],
            "notableProjects": ["Warehouse automation", "Last-mile cost optimization"],
            "publications": ["Omnichannel fulfillment playbook"],
        },
        "expertiseSummary": "Built omni-channel fulfillment and optimized last-mile for high-volume retail.",
        "topicKeywords": ["fulfillment", "automation", "last-mile", "inventory", "cost-to-serve"],
        "availability": "Available next week",
        "cidCleared": False,
        "complianceFlags": ["No MNPI", "No competitor-sensitive topics"],
    },
    {
        "id": "EXP-003",
        "name": "Priya Nair",
        "headline": "Chief Data Officer, Digital Bank",
        "industryTags": ["FinTech", "SaaS"],
        "functionTags": ["Data/AI", "Risk/Compliance"],
        "roleLevel": "CxO",
        "yearsExperience": 20,
        "geography": "Europe",
        "languages": ["English", "Hindi"],
        "ratePerHour": 1200,
        "credentials": {
            "education": "PhD, Computer Science",
            "formerCompanies": ["Lumen Bank", "CoreNova"],
            "notableProjects": ["ML risk scoring platform", "Data governance redesign"],
            "publications": ["Responsible AI in financial services"],
        },
        "expertiseSummary": "Led AI risk models and data governance in regulated FinTech environments.",
        "topicKeywords": ["risk", "model governance", "ml", "regulation", "data quality"],
        "availability": "Limited availability",
        "cidCleared": True,
        "complianceFlags": ["No MNPI", "No confidential client info"],
    },
    {
        "id": "EXP-004",
        "name": "Alex Chen",
        "headline": "VP GTM, Enterprise SaaS",
        "industryTags": ["SaaS"],
        "functionTags": ["GTM", "Sales", "Marketing"],
        "roleLevel": "VP",
        "yearsExperience": 16,
        "geography": "North America",
        "languages": ["English", "Mandarin"],
        "ratePerHour": 950,
        "credentials": {
            "education": "MBA, Kellogg",
            "formerCompanies": ["CloudForge", "RevenueLoop"],
            "notableProjects": ["PLG to enterprise expansion", "Channel partner buildout"],
            "publications": ["Enterprise GTM playbook"],
        },
        "expertiseSummary": "Scaled enterprise SaaS revenue and built partner ecosystems.",
        "topicKeywords": ["gtm", "enterprise", "partners", "sales", "plg"],
        "availability": "Available in 3 weeks",
        "cidCleared": False,
        "complianceFlags": ["No confidential client info"],
    },
    {
        "id": "EXP-005",
        "name": "Leila Haddad",
        "headline": "Strategy Lead, Energy Transition",
        "industryTags": ["Energy", "Public Sector"],
        "functionTags": ["Strategy", "Finance"],
        "roleLevel": "Director",
        "yearsExperience": 14,
        "geography": "Middle East",
        "languages": ["Arabic", "English"],
        "ratePerHour": 500,
        "credentials": {
            "education": "MSc, Economics",
            "formerCompanies": ["Gulf Energy", "Noria Capital"],
            "notableProjects": ["Renewables portfolio strategy", "Hydrogen investment case"],
            "publications": ["Energy transition financing"],
        },
        "expertiseSummary": "Developed capital allocation strategies for energy transition portfolios.",
        "topicKeywords": ["renewables", "hydrogen", "capex", "portfolio", "policy"],
        "availability": "Available next week",
        "cidCleared": True,
        "complianceFlags": ["No MNPI", "No competitor-sensitive topics"],
    },
    {
        "id": "EXP-006",
        "name": "Michael Ochoa",
        "headline": "Director of Operations, Global Airline",
        "industryTags": ["Travel", "Logistics"],
        "functionTags": ["Operations", "Customer Experience"],
        "roleLevel": "Director",
        "yearsExperience": 17,
        "geography": "North America",
        "languages": ["English"],
        "ratePerHour": 480,
        "credentials": {
            "education": "BS, Aerospace Engineering",
            "formerCompanies": ["AeroWorld"],
            "notableProjects": ["Turnaround time optimization", "Irregular ops playbooks"],
            "publications": ["Operational resilience in aviation"],
        },
        "expertiseSummary": "Improved airline operational reliability and passenger experience.",
        "topicKeywords": ["irrops", "turnaround", "nps", "on-time", "capacity planning"],
        "availability": "Available in 2 weeks",
        "cidCleared": False,
        "complianceFlags": ["No confidential client info"],
    },
    {
        "id": "EXP-007",
        "name": "Nora Svensson",
        "headline": "CFO, Consumer Goods Group",
        "industryTags": ["Consumer Goods", "Retail"],
        "functionTags": ["Finance", "Strategy"],
        "roleLevel": "CxO",
        "yearsExperience": 22,
        "geography": "Europe",
        "languages": ["English", "Swedish"],
        "ratePerHour": 1300,
        "credentials": {
            "education": "MBA, INSEAD",
            "formerCompanies": ["Nordic Brands", "FreshVale"],
            "notableProjects": ["Margin expansion program", "Portfolio divestiture"],
            "publications": ["Value creation in CPG"],
        },
        "expertiseSummary": "Led portfolio and margin transformation in consumer goods.",
        "topicKeywords": ["margin", "portfolio", "pricing", "cost takeout", "mix"],
        "availability": "Limited availability",
        "cidCleared": True,
        "complianceFlags": ["No MNPI", "No confidential client info"],
    },
    {
        "id": "EXP-008",
        "name": "Grace Kim",
        "headline": "Product Leader, B2C Mobile",
        "industryTags": ["Media", "SaaS"],
        "functionTags": ["Product", "Marketing"],
        "roleLevel": "Director",
        "yearsExperience": 12,
        "geography": "APAC",
        "languages": ["Korean", "English"],
        "ratePerHour": 380,
        "credentials": {
            "education": "BS, Computer Science",
            "formerCompanies": ["PulseStream", "DailyWave"],
            "notableProjects": ["Subscription growth", "Onboarding redesign"],
            "publications": ["Retention metrics for mobile apps"],
        },
        "expertiseSummary": "Scaled consumer subscription products and retention programs.",
        "topicKeywords": ["retention", "subscription", "onboarding", "activation", "ltv"],
        "availability": "Available next week",
        "cidCleared": False,
        "complianceFlags": ["No confidential client info"],
    },
    {
        "id": "EXP-009",
        "name": "Ravi Deshmukh",
        "headline": "VP Supply Chain, Manufacturing",
        "industryTags": ["Manufacturing", "Automotive"],
        "functionTags": ["Supply Chain", "Operations"],
        "roleLevel": "VP",
        "yearsExperience": 19,
        "geography": "APAC",
        "languages": ["English", "Hindi"],
        "ratePerHour": 700,
        "credentials": {
            "education": "MEng, Mechanical Engineering",
            "formerCompanies": ["AutoMotion", "PrecisionWorks"],
            "notableProjects": ["Supplier risk program", "Lean network redesign"],
            "publications": ["Resilient supply networks"],
        },
        "expertiseSummary": "Led supplier risk and network redesign across automotive plants.",
        "topicKeywords": ["supplier risk", "lean", "network", "inventory", "sourcing"],
        "availability": "Available in 3 weeks",
        "cidCleared": True,
        "complianceFlags": ["No MNPI", "No competitor-sensitive topics"],
    },
    {
        "id": "EXP-010",
        "name": "Hannah Clark",
        "headline": "Director, Public Sector Digital Transformation",
        "industryTags": ["Public Sector"],
        "functionTags": ["Digital Transformation", "Operations"],
        "roleLevel": "Director",
        "yearsExperience": 13,
        "geography": "North America",
        "languages": ["English", "French"],
        "ratePerHour": 460,
        "credentials": {
            "education": "MPA",
            "formerCompanies": ["CivicTech Labs"],
            "notableProjects": ["Citizen service portal", "Case management modernization"],
            "publications": ["Digital government delivery"],
        },
        "expertiseSummary": "Modernized government service delivery with agile implementation.",
        "topicKeywords": ["digital", "citizen services", "agile", "modernization", "workflow"],
        "availability": "Available next week",
        "cidCleared": False,
        "complianceFlags": ["No confidential client info"],
    },
    {
        "id": "EXP-011",
        "name": "Omar Farouk",
        "headline": "Risk and Compliance Head, InsurTech",
        "industryTags": ["Insurance", "FinTech"],
        "functionTags": ["Risk/Compliance", "Data/AI"],
        "roleLevel": "Director",
        "yearsExperience": 11,
        "geography": "Europe",
        "languages": ["English", "Arabic"],
        "ratePerHour": 520,
        "credentials": {
            "education": "JD, Compliance",
            "formerCompanies": ["ShieldSure", "NorthBridge"],
            "notableProjects": ["Model risk framework", "Reg reporting automation"],
            "publications": ["RegTech best practices"],
        },
        "expertiseSummary": "Built compliance automation and model risk frameworks for insurers.",
        "topicKeywords": ["compliance", "regtech", "model risk", "reporting", "audit"],
        "availability": "Available in 2 weeks",
        "cidCleared": True,
        "complianceFlags": ["No MNPI", "No confidential client info"],
    },
    {
        "id": "EXP-012",
        "name": "Elena Petrova",
        "headline": "VP Marketing, Telecom",
        "industryTags": ["Telecom"],
        "functionTags": ["Marketing", "Sales"],
        "roleLevel": "VP",
        "yearsExperience": 17,
        "geography": "Europe",
        "languages": ["English", "Russian"],
        "ratePerHour": 640,
        "credentials": {
            "education": "MBA, London Business School",
            "formerCompanies": ["EuroTel", "SignalNet"],
            "notableProjects": ["ARPU growth program", "Churn reduction"],
            "publications": ["Telecom growth levers"],
        },
        "expertiseSummary": "Drove ARPU uplift and churn reduction in mature telecom markets.",
        "topicKeywords": ["arpu", "churn", "bundling", "campaigns", "retention"],
        "availability": "Available in 4 weeks",
        "cidCleared": False,
        "complianceFlags": ["No confidential client info"],
    },
    {
        "id": "EXP-013",
        "name": "Jonas Becker",
        "headline": "Head of Procurement, Industrial Manufacturing",
        "industryTags": ["Manufacturing"],
        "functionTags": ["Procurement", "Supply Chain"],
        "roleLevel": "Director",
        "yearsExperience": 16,
        "geography": "Europe",
        "languages": ["German", "English"],
        "ratePerHour": 430,
        "credentials": {
            "education": "MBA, Mannheim",
            "formerCompanies": ["SteelCore", "AlphaMach"],
            "notableProjects": ["Strategic sourcing program", "Supplier consolidation"],
            "publications": ["Should-cost modeling"],
        },
        "expertiseSummary": "Led strategic sourcing and should-cost modeling in heavy industry.",
        "topicKeywords": ["sourcing", "should-cost", "supplier", "negotiation", "commodities"],
        "availability": "Available next week",
        "cidCleared": True,
        "complianceFlags": ["No MNPI"],
    },
    {
        "id": "EXP-014",
        "name": "Alicia Romero",
        "headline": "Growth VP, Consumer FinTech",
        "industryTags": ["FinTech", "Consumer Goods"],
        "functionTags": ["GTM", "Marketing", "Product"],
        "roleLevel": "VP",
        "yearsExperience": 13,
        "geography": "North America",
        "languages": ["English", "Spanish"],
        "ratePerHour": 780,
        "credentials": {
            "education": "BA, Economics",
            "formerCompanies": ["PaySpark", "QuickCard"],
            "notableProjects": ["Cashback repositioning", "App funnel optimization"],
            "publications": ["FinTech growth loops"],
        },
        "expertiseSummary": "Scaled consumer FinTech growth through funnel and product-led tactics.",
        "topicKeywords": ["growth", "funnels", "acquisition", "activation", "pricing"],
        "availability": "Available in 2 weeks",
        "cidCleared": False,
        "complianceFlags": ["No confidential client info"],
    },
    {
        "id": "EXP-015",
        "name": "Tariq Malik",
        "headline": "Director, Hospital Operations",
        "industryTags": ["Healthcare"],
        "functionTags": ["Operations", "Customer Experience"],
        "roleLevel": "Director",
        "yearsExperience": 14,
        "geography": "Middle East",
        "languages": ["English"],
        "ratePerHour": 390,
        "credentials": {
            "education": "MHA",
            "formerCompanies": ["CityCare Hospitals"],
            "notableProjects": ["OR throughput optimization", "ED flow redesign"],
            "publications": ["Lean operations in hospitals"],
        },
        "expertiseSummary": "Improved patient flow and clinical throughput in large hospitals.",
        "topicKeywords": ["patient flow", "throughput", "bed management", "lean", "access"],
        "availability": "Available next week",
        "cidCleared": True,
        "complianceFlags": ["No confidential client info"],
    },
    {
        "id": "EXP-016",
        "name": "Jordan Wells",
        "headline": "CIO Advisor, Retail Technology",
        "industryTags": ["Retail", "SaaS"],
        "functionTags": ["Digital Transformation", "Data/AI"],
        "roleLevel": "CxO",
        "yearsExperience": 21,
        "geography": "North America",
        "languages": ["English"],
        "ratePerHour": 1100,
        "credentials": {
            "education": "MS, Information Systems",
            "formerCompanies": ["RetailHub", "ShopSphere"],
            "notableProjects": ["Cloud POS migration", "Customer data platform rollout"],
            "publications": ["Omnichannel data foundations"],
        },
        "expertiseSummary": "Led retail modernization and data platform programs.",
        "topicKeywords": ["cloud", "pos", "cdp", "omnichannel", "data platform"],
        "availability": "Available in 3 weeks",
        "cidCleared": False,
        "complianceFlags": ["No MNPI", "No confidential client info"],
    },
    {
        "id": "EXP-017",
        "name": "Bianca Rossi",
        "headline": "Director of Sales Excellence, B2B Telecom",
        "industryTags": ["Telecom"],
        "functionTags": ["Sales", "Operations"],
        "roleLevel": "Director",
        "yearsExperience": 12,
        "geography": "Europe",
        "languages": ["Italian", "English"],
        "ratePerHour": 410,
        "credentials": {
            "education": "MBA",
            "formerCompanies": ["MetroTel"],
            "notableProjects": ["Sales playbook redesign", "Quota setting overhaul"],
            "publications": ["B2B telecom sales motions"],
        },
        "expertiseSummary": "Built repeatable sales motions and quota models for B2B telecom.",
        "topicKeywords": ["sales motion", "quota", "pipeline", "enablement", "coverage"],
        "availability": "Available next week",
        "cidCleared": True,
        "complianceFlags": ["No confidential client info"],
    },
    {
        "id": "EXP-018",
        "name": "Marcus Green",
        "headline": "Director, Logistics Analytics",
        "industryTags": ["Logistics", "Retail"],
        "functionTags": ["Data/AI", "Operations"],
        "roleLevel": "Director",
        "yearsExperience": 10,
        "geography": "North America",
        "languages": ["English"],
        "ratePerHour": 360,
        "credentials": {
            "education": "MS, Data Science",
            "formerCompanies": ["ShipTrack", "FastCart"],
            "notableProjects": ["Route optimization ML", "Delivery ETA forecasting"],
            "publications": ["Applied analytics in logistics"],
        },
        "expertiseSummary": "Built analytics platforms for routing and ETA accuracy.",
        "topicKeywords": ["routing", "eta", "forecasting", "optimization", "cost"],
        "availability": "Available next week",
        "cidCleared": False,
        "complianceFlags": ["No confidential client info"],
    },
    {
        "id": "EXP-019",
        "name": "Camila Ortiz",
        "headline": "Director, Consumer Insights",
        "industryTags": ["Consumer Goods", "Retail"],
        "functionTags": ["Marketing", "Strategy"],
        "roleLevel": "Director",
        "yearsExperience": 12,
        "geography": "LATAM",
        "languages": ["Spanish", "English"],
        "ratePerHour": 390,
        "credentials": {
            "education": "MBA",
            "formerCompanies": ["BellaFoods", "FreshVale"],
            "notableProjects": ["Brand repositioning", "Category growth diagnostics"],
            "publications": ["Shopper behavior shifts"],
        },
        "expertiseSummary": "Led category growth and consumer insight programs in CPG.",
        "topicKeywords": ["consumer insights", "category", "brand", "pricing", "channels"],
        "availability": "Available in 2 weeks",
        "cidCleared": True,
        "complianceFlags": ["No confidential client info"],
    },
    {
        "id": "EXP-020",
        "name": "Ethan Brooks",
        "headline": "Senior Manager, SaaS Finance",
        "industryTags": ["SaaS"],
        "functionTags": ["Finance", "Pricing"],
        "roleLevel": "Manager",
        "yearsExperience": 9,
        "geography": "North America",
        "languages": ["English"],
        "ratePerHour": 290,
        "credentials": {
            "education": "CPA",
            "formerCompanies": ["CloudForge"],
            "notableProjects": ["Usage-based pricing model", "Revenue forecasting"],
            "publications": ["SaaS unit economics"],
        },
        "expertiseSummary": "Built SaaS pricing and unit economics frameworks.",
        "topicKeywords": ["unit economics", "usage-based", "forecasting", "ltv", "cac"],
        "availability": "Available next week",
        "cidCleared": False,
        "complianceFlags": ["No confidential client info"],
    },
    {
        "id": "EXP-021",
        "name": "Mei Tan",
        "headline": "Director, Clinical Data & AI",
        "industryTags": ["Healthcare", "SaaS"],
        "functionTags": ["Data/AI", "Product"],
        "roleLevel": "Director",
        "yearsExperience": 11,
        "geography": "APAC",
        "languages": ["English", "Mandarin"],
        "ratePerHour": 540,
        "credentials": {
            "education": "PharmD",
            "formerCompanies": ["ClinTech", "MedNova"],
            "notableProjects": ["Clinical NLP pipeline", "Real-world evidence platform"],
            "publications": ["AI in clinical data pipelines"],
        },
        "expertiseSummary": "Developed AI-driven clinical data products and evidence platforms.",
        "topicKeywords": ["clinical data", "nlp", "real-world evidence", "ai", "product"],
        "availability": "Available in 3 weeks",
        "cidCleared": True,
        "complianceFlags": ["No MNPI", "No confidential client info"],
    },
    {
        "id": "EXP-022",
        "name": "George Patel",
        "headline": "VP Strategy, Insurance",
        "industryTags": ["Insurance"],
        "functionTags": ["Strategy", "Pricing"],
        "roleLevel": "VP",
        "yearsExperience": 18,
        "geography": "North America",
        "languages": ["English"],
        "ratePerHour": 820,
        "credentials": {
            "education": "MBA, Booth",
            "formerCompanies": ["ShieldSure"],
            "notableProjects": ["Usage-based insurance", "Distribution redesign"],
            "publications": ["Insurance innovation playbook"],
        },
        "expertiseSummary": "Led pricing and distribution strategy in P&C insurance.",
        "topicKeywords": ["insurance", "pricing", "distribution", "innovation", "telematics"],
        "availability": "Available in 2 weeks",
        "cidCleared": False,
        "complianceFlags": ["No confidential client info"],
    },
    {
        "id": "EXP-023",
        "name": "Fatima El-Sayed",
        "headline": "Director, Education Technology",
        "industryTags": ["Education", "SaaS"],
        "functionTags": ["Product", "GTM"],
        "roleLevel": "Director",
        "yearsExperience": 10,
        "geography": "Middle East",
        "languages": ["Arabic", "English"],
        "ratePerHour": 360,
        "credentials": {
            "education": "MEd",
            "formerCompanies": ["LearnLoop", "EduSpark"],
            "notableProjects": ["District rollout strategy", "Teacher enablement"],
            "publications": ["EdTech adoption drivers"],
        },
        "expertiseSummary": "Scaled EdTech adoption and product launches for schools.",
        "topicKeywords": ["adoption", "rollout", "teacher enablement", "gtm", "product"],
        "availability": "Available next week",
        "cidCleared": True,
        "complianceFlags": ["No confidential client info"],
    },
    {
        "id": "EXP-024",
        "name": "Isaac Moore",
        "headline": "Director, Automotive Pricing",
        "industryTags": ["Automotive", "Manufacturing"],
        "functionTags": ["Pricing", "Strategy"],
        "roleLevel": "Director",
        "yearsExperience": 14,
        "geography": "North America",
        "languages": ["English"],
        "ratePerHour": 610,
        "credentials": {
            "education": "MBA",
            "formerCompanies": ["AutoMotion"],
            "notableProjects": ["Incentive redesign", "Dealer margin strategy"],
            "publications": ["Automotive pricing dynamics"],
        },
        "expertiseSummary": "Designed incentive and dealer margin strategies in automotive.",
        "topicKeywords": ["incentives", "dealer", "pricing", "margin", "channel"],
        "availability": "Available in 2 weeks",
        "cidCleared": False,
        "complianceFlags": ["No MNPI"],
    },
    {
        "id": "EXP-025",
        "name": "Sophia Grant",
        "headline": "VP HR Transformation",
        "industryTags": ["Public Sector", "Healthcare"],
        "functionTags": ["HR", "Digital Transformation"],
        "roleLevel": "VP",
        "yearsExperience": 16,
        "geography": "Europe",
        "languages": ["English"],
        "ratePerHour": 520,
        "credentials": {
            "education": "MA, Organizational Psychology",
            "formerCompanies": ["CivicTech Labs", "CityCare Hospitals"],
            "notableProjects": ["Workforce planning model", "HRIS modernization"],
            "publications": ["Future of public workforce"],
        },
        "expertiseSummary": "Led workforce planning and HR digital modernization.",
        "topicKeywords": ["workforce", "hris", "planning", "change", "capability"],
        "availability": "Available in 3 weeks",
        "cidCleared": True,
        "complianceFlags": ["No confidential client info"],
    },
]
